# Generated by Django 4.0.4 on 2022-05-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'People', 'verbose_name_plural': 'Peoples'},
        ),
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.CharField(max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='people',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='people',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='people',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
    ]
