# Generated by Django 4.0.4 on 2022-06-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='В избранное'),
        ),
    ]
